# Generated by Django 4.2.7 on 2023-12-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuarte", "0009_instrumento_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumento",
            name="usuario",
        ),
    ]
