# Generated by Django 4.2.7 on 2023-12-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nuarte", "0012_remove_historico_notificacao_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="historico",
            name="notificacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nuarte.notificacao",
            ),
        ),
    ]
